<a href="https://colab.research.google.com/github/asadiv/Pytorch/blob/main/00_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [25]:
import torch
import numpy as np
import pandas as pd

print(torch.__version__)
print(np.__version__)


2.9.0+cu126
2.0.2


In [26]:
scalar = torch.tensor([5])
scalar

tensor([5])

In [27]:
# its a 3x3 and 2 dim cuz 2 brackets
Matrix = torch.tensor([[1,2,3],
                       [4,5,6],
                       [7,8,9]])
Matrix.size()
Matrix.shape
Matrix.ndim

2

In [28]:
# its now a 1x3x3 and 3 dim cuz 3 brackets
Matrix = torch.tensor([[[1,2,3],
                       [4,5,6],
                       [7,8,9]]])
Matrix.size()
Matrix.shape
# Matrix.ndim

torch.Size([1, 3, 3])

In [29]:
# arange  -   using zeros and ones   -    copying shapes of other tensors
one_to_ten = torch.arange(1,11,1)
one_to_ten
all_zeros = torch.zeros(3,4)
ten_zeros = torch.zeros_like(input=one_to_ten)
one_to_ten, all_zeros , ten_zeros

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]))

In [30]:
# Tensor Attributes and 3 common issues->
# 1. tensor dtype is not right
# 1. tensor shape is not right
# 1. tensor is not on right device

tens = torch.tensor([1,2,3],  dtype=torch.float32,   device='cpu',  requires_grad=False)
tens = torch.tensor([1,2,3],  dtype=torch.float16,   device='cuda',  requires_grad=False)

In [31]:
# getting info from tensors
some_tensor = torch.rand(3, 4)

# Find out details about it
print(some_tensor)
# following are attributes of tensor
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.2081, 0.9298, 0.7231, 0.7423],
        [0.5263, 0.2437, 0.5846, 0.0332],
        [0.1387, 0.2422, 0.8155, 0.7932]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [32]:
# Element-wise multiplication (each element multiplies its equivalent, index 0->0, 1->1, 2->2)
tensor = torch.tensor([1, 2, 3])
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)



# Shapes need to be in the right way
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)

# torch.matmul(tensor_A, tensor_B) # (this will error)



# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])
Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])


In [33]:
#  min  -   max   -   mean
x = torch.arange(1,10,1)
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") # this will error
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")

# torch.max(x), torch.min(x), torch.mean(x.type(torch.float32)), torch.sum(x) #can use this too

Minimum: 1
Maximum: 9
Mean: 5.0
Sum: 45


In [34]:
# Create a tensor
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


In [35]:
# reshape  -   view
import torch
x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [36]:
# chnage shape
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [37]:
# Change view (keeps same data as original but changes view)
# view requires data to be contigous, if u take transpose then change view will cause error.
z = x.view(1, 7)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [38]:
# Changing z changes x
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

In [39]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0) # at dim=0 : 4x7 at dim=1: 7x4
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.]])

In [40]:
# VSTACK : Stack tensors in sequence vertically (row wise).
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])
print(torch.vstack((a,b)))
a = torch.tensor([[1],[2],[3]])
b = torch.tensor([[4],[5],[6]])
torch.vstack((a,b)) # 3+3 rows of a and b = 6 rows


tensor([[1, 2, 3],
        [4, 5, 6]])


tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

In [41]:
# Hstack: Stack tensors in sequence horizontally (column wise).

a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])
print(torch.hstack((a,b)))
a = torch.tensor([[1],[2],[3]])
b = torch.tensor([[4],[5],[6]])
torch.hstack((a,b))  # 1+1 cols of a and b = 2 cols in result

tensor([1, 2, 3, 4, 5, 6])


tensor([[1, 4],
        [2, 5],
        [3, 6]])

In [42]:
#  Squeeze removes all dims that are 1
print(f"Previous tensor: {x_reshaped}") #x_shaped is 1x7
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")  # just 7

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
Previous shape: torch.Size([1, 7])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
New shape: torch.Size([7])


In [43]:
#  unsqueeze adds dim1 at specific index
print(f"Previous tensor: {x_squeezed}") #just 7
print(f"Previous shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0) # now 1x7  if dim=1: then 7x1
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
Previous shape: torch.Size([7])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
New shape: torch.Size([1, 7])


In [44]:
# using permute to chnages axis
x_original = torch.rand(size=(224, 224, 3))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->2, 1->0, 2->1

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [45]:
# numpy to tensor
import numpy as np
import torch
arr = np.arange(1.,8.)
tensor = torch.from_numpy(arr)  # shares same memory - dtype will be float64 not 32 cuz np has 64 default
arr[0] = 8  # chnage reflected in tensor as this chnages actual memeory
# arr =arr+1 #change doesnt reflect in tensor cuz it creates a new arr its not the old anymore
arr,tensor

(array([8., 2., 3., 4., 5., 6., 7.]),
 tensor([8., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [46]:
#tensor to numpy

tensor = torch.ones(7)
np_arr = tensor.numpy()
tensor[0] = 9 # chnage reflected
np_arr,tensor

(array([9., 1., 1., 1., 1., 1., 1.], dtype=float32),
 tensor([9., 1., 1., 1., 1., 1., 1.]))

In [47]:
# reproducibility (so you can perform repeatable experiments.)
# when will it gen same nums:
# 1. same pytorch version
# 2. same device (cpu,gpu)
# 3. same seed
randSeed = 0
torch.manual_seed(seed = randSeed)  # each time seed is set to same number it will gen same rand nums
tensor1 = torch.rand(3,4)
torch.manual_seed(seed = randSeed)
tensor2 = torch.rand(3,4)
print(tensor1)
print(tensor2)
print(tensor1 == tensor2)

tensor([[0.4963, 0.7682, 0.0885, 0.1320],
        [0.3074, 0.6341, 0.4901, 0.8964],
        [0.4556, 0.6323, 0.3489, 0.4017]])
tensor([[0.4963, 0.7682, 0.0885, 0.1320],
        [0.3074, 0.6341, 0.4901, 0.8964],
        [0.4556, 0.6323, 0.3489, 0.4017]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [48]:
# device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [49]:
x= torch.rand(3,4).to(device)
x.device

device(type='cuda', index=0)