<a href="https://colab.research.google.com/github/asadiv/Pytorch/blob/main/00_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch
import numpy as np
import pandas as pd

print(torch.__version__)
print(np.__version__)


2.9.0+cu126
2.0.2


In [4]:
scalar = torch.tensor([5])
scalar

tensor([5])

In [5]:
# its a 3x3 and 2 dim cuz 2 brackets
Matrix = torch.tensor([[1,2,3],
                       [4,5,6],
                       [7,8,9]])
Matrix.size()
Matrix.shape
Matrix.ndim

2

In [6]:
# its now a 1x3x3 and 3 dim cuz 3 brackets
Matrix = torch.tensor([[[1,2,3],
                       [4,5,6],
                       [7,8,9]]])
Matrix.size()
Matrix.shape
# Matrix.ndim

torch.Size([1, 3, 3])

In [11]:
# arange  -   using zeros and ones   -    copying shapes of other tensors
one_to_ten = torch.arange(1,11,1)
one_to_ten
all_zeros = torch.zeros(3,4)
ten_zeros = torch.zeros_like(input=one_to_ten)
one_to_ten, all_zeros , ten_zeros

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]))

In [12]:
# Tensor Attributes and 3 common issues->
# 1. tensor dtype is not right
# 1. tensor shape is not right
# 1. tensor is not on right device

tens = torch.tensor([1,2,3],  dtype=torch.float32,   device='cpu',  requires_grad=False)
tens = torch.tensor([1,2,3],  dtype=torch.float16,   device='cuda',  requires_grad=False)

In [ ]:
# getting info from tensors
some_tensor = torch.rand(3, 4)

# Find out details about it
print(some_tensor)
# following are attributes of tensor
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU