<a href="https://colab.research.google.com/github/asadiv/Pytorch/blob/main/00_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch
import numpy as np
import pandas as pd

print(torch.__version__)
print(np.__version__)


2.9.0+cu126
2.0.2


In [4]:
scalar = torch.tensor([5])
scalar

tensor([5])

In [5]:
# its a 3x3 and 2 dim cuz 2 brackets
Matrix = torch.tensor([[1,2,3],
                       [4,5,6],
                       [7,8,9]])
Matrix.size()
Matrix.shape
Matrix.ndim

2

In [6]:
# its now a 1x3x3 and 3 dim cuz 3 brackets
Matrix = torch.tensor([[[1,2,3],
                       [4,5,6],
                       [7,8,9]]])
Matrix.size()
Matrix.shape
# Matrix.ndim

torch.Size([1, 3, 3])

In [7]:
# arange  -   using zeros and ones   -    copying shapes of other tensors
one_to_ten = torch.arange(1,11,1)
one_to_ten
all_zeros = torch.zeros(3,4)
ten_zeros = torch.zeros_like(input=one_to_ten)
one_to_ten, all_zeros , ten_zeros

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]))

In [8]:
# Tensor Attributes and 3 common issues->
# 1. tensor dtype is not right
# 1. tensor shape is not right
# 1. tensor is not on right device

tens = torch.tensor([1,2,3],  dtype=torch.float32,   device='cpu',  requires_grad=False)
tens = torch.tensor([1,2,3],  dtype=torch.float16,   device='cuda',  requires_grad=False)

In [9]:
# getting info from tensors
some_tensor = torch.rand(3, 4)

# Find out details about it
print(some_tensor)
# following are attributes of tensor
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.0597, 0.3806, 0.4894, 0.4661],
        [0.7268, 0.4304, 0.3524, 0.8302],
        [0.4088, 0.6763, 0.0190, 0.4510]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [10]:
# Element-wise multiplication (each element multiplies its equivalent, index 0->0, 1->1, 2->2)
tensor = torch.tensor([1, 2, 3])
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)



# Shapes need to be in the right way
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)

# torch.matmul(tensor_A, tensor_B) # (this will error)



# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])
Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])


In [11]:
#  min  -   max   -   mean
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") # this will error
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")

# torch.max(x), torch.min(x), torch.mean(x.type(torch.float32)), torch.sum(x) #can use this too

NameError: name 'x' is not defined

In [ ]:
# Create a tensor
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")